name: Chaptrix Unified Workflow

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up environment variables
        run: |
          touch .env
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
          fi
          if [ -n "${{ secrets.DISCORD_BOT_TOKEN }}" ]; then
            echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env
          fi
          if [ -n "${{ secrets.DISCORD_CHANNEL_ID }}" ]; then
            echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> .env
          fi
          if [ -n "${{ secrets.GOOGLE_CREDENTIALS }}" ]; then
            echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          fi
          
      - name: Run unified workflow
        run: python unified_workflow.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add comics.json
          git commit -m "Update comics data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}