name: Chaptrix Unified Workflow

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up environment
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          echo "DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL" > .env
          echo "DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN" >> .env
          echo "DISCORD_CHANNEL_ID=$DISCORD_CHANNEL_ID" >> .env
      
      - name: Set up Google Drive credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
          
      - name: Run unified workflow
        run: python unified_workflow.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add comics.json
          git commit -m "Update comics data" || echo "No changes to commit"
          git push